'''
Submitter for the SLURM system (PSI Tier-3) -- Bc signal MC, production of 21 Sep 2026.

Derived from submitter_bc_mc_pnfs.py. This production adds, with respect to the
covflow_v2 one:

  * Bc lifetime weights       gen_bc_ctau_weight{,_up,_down}   (always on for MC,
                              nothing to configure)
  * Hammer FF weights         hammer_weight, hammer_ff_ev00..14_{up,dn},
                              hammer_status: Kiselev -> Harrison-2024, central +
                              the 2 x 15 eigenvariations of the validated card
  * track covariance fix      --covflow cf_block_ref (as in covflow_v2)

Run from Bmmm/Analysis/test/rjpsi, in a shell where you have done `cmsenv`:

    python3 covariance/submitter_bc_mc_pnfs_21sep26.py --test 2     # first!
    python3 covariance/submitter_bc_mc_pnfs_21sep26.py --dry-run    # scripts only
    python3 covariance/submitter_bc_mc_pnfs_21sep26.py              # everything

--test N submits only the first N chunks into <out_dir>_test. Do that first: the
inline Hammer path with BGLVar and 30 eigenvariations has never run at scale, so
job time and memory are unknown. Hammer integrates the BGLVar rate tensor once
per job (minutes in the validation), and each Bc -> J/psi l nu event then costs
31 set_ff_eigenvectors + get_weight calls. Read the test job's wall time,
hammer_status and <hammer_weight> before launching the rest.

Everything that would make EVERY job fail is checked here, at submission time,
instead of 700 times on the batch: the FF card (P1 convention and a validated
covariance), the Hammer install, cf_block_ref, the entry point.

Direct submission: the FWLite ntuplizer runs natively under the current CMSSW
release (el9 matches the worker nodes; no container).
'''

import argparse
import datetime
import hashlib
import json
import os
import shutil
import subprocess
from glob import glob

ap = argparse.ArgumentParser(description=__doc__,
                             formatter_class=argparse.RawDescriptionHelpFormatter)
ap.add_argument('--test', type=int, default=0, metavar='N',
                help='submit only the first N chunks, into <out_dir>_test')
ap.add_argument('--dry-run', action='store_true',
                help='write the job scripts and the provenance, submit nothing')
args = ap.parse_args()

resubmit = False
toresubmit = []          # chunk indices, used only when resubmit = True

old_files = []
files = []

with open('files_bc_skim_15jun26.txt') as f:
    ifiles = f.read().splitlines()
    ifiles = ['root://t3dcachedb03.psi.ch:1094//'+ifile for ifile in ifiles if ifile not in old_files]
    files += ifiles

files_per_job = 1
chunks = list(map(list, list(zip(*[iter(files)]*files_per_job))))

if len(files)%files_per_job!=0:
    last_idx = len(files)%files_per_job
    chunks += [files[-last_idx:]]

queue = 'standard'; time = 720
# queue = 'short'   ; time = 60
# queue = 'long'    ; time = 10080

# out_dir = 'RJpsi_09Sep2026_notrig_BcToJPsiMuMu_inclusive_covflow_v2'
out_dir = 'RJpsi_21Sep2026_notrig_BcToJPsiMuMu_inclusive_covflow_hammer_ctau_v1'
if args.test:
    out_dir += '_test'

out_file_name = 'rjpsi'

cfg = 'inspector_rjpsi.py'

# ------------------------------------------------------------------------------------------
# NEW (21 Sep 2026): Hammer and the FF card
# ------------------------------------------------------------------------------------------
HAMMER_PREFIX = '/work/manzoni/hammer'
HAMMER_ENV    = HAMMER_PREFIX + '/hammer_env.sh'   # generated by install_hammer.sh (bash)
CARD_NAME     = 'harrison_bglvar.json'
COVFLOW_REF   = os.path.join(os.getcwd(), 'cf_block_ref')

# CMSSW release to set up inside the job, captured from the current shell.
cmssw_base = os.environ.get('CMSSW_BASE', '')
scram_arch = os.environ.get('SCRAM_ARCH', '')
if not cmssw_base:
    raise RuntimeError('CMSSW_BASE is not set -- run `cmsenv` in your CMSSW_X_Y_Z/src before launching this submitter.')

##########################################################################################
# PREFLIGHT: anything that would fail every job is caught here, once
##########################################################################################

def die(msg):
    raise SystemExit('[PREFLIGHT] ' + msg)

if not os.path.isfile(cfg):
    die('%s not found in %s: run the submitter from Bmmm/Analysis/test/rjpsi.' % (cfg, os.getcwd()))
if not os.path.exists(COVFLOW_REF):
    die('covflow reference %s not found.' % COVFLOW_REF)
if not os.path.isfile(HAMMER_ENV):
    die('%s not found: Hammer is not installed where the jobs expect it '
        '(run install_hammer.sh, or fix HAMMER_PREFIX).' % HAMMER_ENV)

# The card is validated with the SAME code the jobs will use: HammerFF.load_card
# checks unitarity and shapes, and P1_CONVENTION is the single source of truth for
# the convention a card must be fitted in. Importing HammerFF does not import
# hammer itself, so this works in any cmsenv'd shell.
from Bmmm.Analysis.HammerFF import P1_CONVENTION, load_card
card_src = os.path.join(cmssw_base, 'src', 'Bmmm', 'Analysis', 'data', CARD_NAME)
if not os.path.isfile(card_src):
    die('FF card %s not found.' % card_src)
card = load_card(card_src)
if card.get('p1_convention') != P1_CONVENTION:
    die('FF card %s is not fitted in the P1 convention Hammer uses (%r, card says %r). '
        'Its tau weights would be biased by ~+1%% on R. Refit it.'
        % (card_src, P1_CONVENTION, card.get('p1_convention')))
if str(card.get('covariance_status', '')).lower() != 'validated':
    die('FF card %s has covariance_status=%r: the jobs would refuse to write the '
        'eigenvariations. Validate the covariance and set it to "validated".'
        % (card_src, card.get('covariance_status')))

##########################################################################################
##########################################################################################

# make output dir
if not os.path.exists(out_dir):
    try:
        os.makedirs('/pnfs/psi.ch/cms/trivcat/store/user/manzoni/'+out_dir)
    except:
        print('pnfs directory exists')
    os.makedirs(out_dir)
    os.makedirs(out_dir + '/logs')
    os.makedirs(out_dir + '/errs')

os.system('cp %s %s' %(cfg, out_dir))

# NEW: snapshot the FF card into the production directory. The jobs read THIS
# copy, so editing or refitting the card in the release later cannot change a
# production that is already running, and the card that made the weights is
# kept next to them.
card_used = os.path.join(os.getcwd(), out_dir, CARD_NAME)
shutil.copy2(card_src, card_used)

# NEW: provenance, written at submission time
def sh(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT,
                                       universal_newlines=True).strip()
    except subprocess.CalledProcessError as exc:
        return '<failed: %s>' % exc.output.strip()

repo = os.path.join(cmssw_base, 'src', 'Bmmm')
dirty = sh('git -C %s status --porcelain --untracked-files=no' % repo)
with open(card_used, 'rb') as fcard:
    card_sha = hashlib.sha256(fcard.read()).hexdigest()
provenance = {
    'submitted'        : datetime.datetime.now().isoformat(timespec='seconds'),
    'out_dir'          : out_dir,
    'cmssw_base'       : cmssw_base,
    'scram_arch'       : scram_arch,
    'bmmm_commit'      : sh('git -C %s rev-parse HEAD' % repo),
    'bmmm_dirty_files' : dirty.splitlines() if dirty else [],
    'n_chunks'         : len(chunks),
    'test'             : args.test,
    'input_list'       : 'files_bc_skim_15jun26.txt',
    'covflow_ref'      : COVFLOW_REF,
    'hammer_env'       : HAMMER_ENV,
    'ff_card'          : {'file': card_used, 'sha256': card_sha,
                          'name': card.get('name'), 'fit_date': card.get('fit_date'),
                          'p1_convention': card.get('p1_convention'),
                          'covariance_status': card.get('covariance_status')},
    'ctau_weights'     : 'tau_MC 0.507 ps -> PDG 0.510 +/- 0.010 ps (gen_bc_ctau_weight*)',
}
with open(os.path.join(out_dir, 'PROVENANCE.json'), 'w') as fprov:
    json.dump(provenance, fprov, indent=1)
if dirty:
    print('[WARN] the Bmmm checkout has uncommitted changes; they are listed in '
          '%s/PROVENANCE.json' % out_dir)
print('#### provenance: Bmmm %s, card %s (sha256 %s...)'
      % (provenance['bmmm_commit'][:10], card.get('fit_date'), card_sha[:12]))

n_submitted = 0
for ijob, ichunk in enumerate(chunks):

    if resubmit:
        if ijob not in toresubmit: continue

    if args.test and ijob >= args.test:
        break

    to_write = '\n'.join([
        '#!/bin/bash',
        '',
        '# --- scratch dir ---',
        'mkdir -p /scratch/manzoni/{scratch_dir}',
        'ls /scratch/manzoni/',
        'FAILED_PARTS=0',
        '',
        '# --- CMSSW runtime (native, no container) ---',
        'export SCRAM_ARCH={scram_arch}',
        'source /cvmfs/cms.cern.ch/cmsset_default.sh',
        'echo ">>>> moving to {dir}"',
        'cd {cmssw_base}/src',
        'echo ">>>> now in $PWD"',
        'eval `scramv1 runtime -sh`',
        'echo ">>>> CMSSW_BASE=$CMSSW_BASE"',
        'echo ">>>> using python: $(which python3)"',
        '',
        '# --- fail loudly if cmsenv did not take effect ---',
        'python3 -c "import sys; print(\'>>>> python startup OK\', sys.version.split()[0])"',
        'if [ $? -ne 0 ]; then',
        '    echo ">>>> FATAL: cmsenv did not take effect (CMSSW python cannot find its standard library). Aborting chunk {ijob}."',
        '    exit 1',
        'fi',
        'which hadd',
        '',
        '# --- NEW: Hammer on the path, after cmsenv (it must not be overridden) ---',
        'source {hammer_env}',
        'python3 -c "import hammer; print(\'>>>> hammer\', getattr(hammer, \'version\', \'?\'), hammer.__file__)"',
        'if [ $? -ne 0 ]; then',
        '    echo ">>>> FATAL: hammer is not importable on this node. Aborting chunk {ijob}."',
        '    exit 1',
        'fi',
        '',
        '# --- grid proxy: stage a private copy that survives the whole job ---',
        'cp $X509_USER_PROXY /scratch/manzoni/{scratch_dir}/x509proxy_{ijob}',
        'chmod 600 /scratch/manzoni/{scratch_dir}/x509proxy_{ijob}',
        'export X509_USER_PROXY=/scratch/manzoni/{scratch_dir}/x509proxy_{ijob}',
        '',
        '# --- run from the output dir so per-job loggers land there ---',
        'cd {dir}',
        'echo ">>>> now running in $PWD"',
        '',
    ]).format(
        dir         = '/'.join([os.getcwd(), out_dir]),
        scratch_dir = out_dir,
        cmssw_base  = cmssw_base,
        scram_arch  = scram_arch,
        hammer_env  = HAMMER_ENV,
        ijob        = ijob,
    )

    for idx, ifile in enumerate(ichunk):
        to_write += (
            'python3 {dir}/{cfg} '
            '--inputFiles={infiles} '
            '--logfreq=5000 '
            '--destination=/scratch/manzoni/{scratch_dir} '
            '--savenontrig '
            '--covflow {covflow} '
            '--hammer {card} '
            '--mc '
            '--skim '
            '--filename={outfile}_chunk{ijob}_part{idx} \n'
            'if [ $? -ne 0 ]; then\n'
            '    echo ">>>> FAILED: part{idx} of chunk{ijob} ({infiles})"\n'
            '    FAILED_PARTS=$((FAILED_PARTS+1))\n'
            'fi\n'
        ).format(
            dir         = '/'.join([os.getcwd(), out_dir]),
            covflow     = COVFLOW_REF,
            card        = card_used,
            scratch_dir = out_dir,
            cfg         = cfg,
            outfile     = out_file_name,
            ijob        = ijob,
            infiles     = ifile,
            idx         = idx,
        )

    to_write += '\n'.join([
        '',
        'ls -latrh /scratch/manzoni/{scratch_dir}',
        'echo ">>>> $FAILED_PARTS part(s) failed for chunk {ijob}"',
        '',
        'if [ $FAILED_PARTS -gt 0 ]; then',
        '    echo ">>>> ABORTING merge and transfer for chunk {ijob}: not all parts succeeded"',
        '    exit 1',
        'fi',
        '',
        'hadd -f -k '
        '/scratch/manzoni/{scratch_dir}/{outfile}_chunk{ijob}.root '
        '/scratch/manzoni/{scratch_dir}/{outfile}_chunk{ijob}_part*.root',
        '',
        'xrdcp '
        '/scratch/manzoni/{scratch_dir}/{outfile}_chunk{ijob}.root '
        'root://t3dcachedb03.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/manzoni/{se_dir}/{outfile}_chunk{ijob}.root',
        '',
        'if [ $? -eq 0 ]; then',
        '    echo ">>>> xrdcp succeeded, cleaning scratch"',
        '    rm -f /scratch/manzoni/{scratch_dir}/{outfile}_chunk{ijob}.root',
        '    rm -f /scratch/manzoni/{scratch_dir}/{outfile}_chunk{ijob}_part*.root',
        'else',
        '    echo ">>>> xrdcp FAILED for chunk {ijob}, scratch files kept for inspection"',
        '    exit 1',
        'fi',
        '',
    ]).format(
        scratch_dir = out_dir,
        outfile     = out_file_name,
        ijob        = ijob,
        se_dir      = out_dir,
    )

    with open("%s/submitter_chunk%d.sh" %(out_dir, ijob), "wt") as flauncher:
        flauncher.write(to_write)

    command_sh_batch = ' '.join([
        'sbatch',
        '-p %s'%queue,
        '--account=t3',
        '-o %s/logs/chunk%d.log' %(out_dir, ijob),
        '-e %s/errs/chunk%d.err' %(out_dir, ijob),
        '--job-name=%d_%s' %(ijob, out_dir),
        '--time=%d'%time,
        '--nodes=1 --ntasks=1 --nodelist=t3wn[80-91]',
        '--mem=4000',
        '%s/submitter_chunk%d.sh' %(out_dir, ijob),
    ])

    print(command_sh_batch)
    if not args.dry_run:
        os.system(command_sh_batch)
    n_submitted += 1

print('#### %s %d chunk(s) of %d into %s'
      % ('wrote (dry run)' if args.dry_run else 'submitted', n_submitted, len(chunks), out_dir))
