branches = [
    'run'               ,
    'lumi'              ,
    'event'             ,
    'npv'               ,

    'mass'              ,
    'mcorr'             ,
    'pt'                ,
    'eta'               ,
    'phi'               ,
    'charge'            ,

    'dr'                ,
    'dr_max'            ,
    'dr_12'             ,
    'dr_13'             ,
    'dr_14'             ,
    'dr_23'             ,
    'dr_24'             ,
    'dr_34'             ,

    'charge_12'         ,
    'charge_13'         ,
    'charge_14'         ,
    'charge_23'         ,
    'charge_24'         ,
    'charge_34'         ,
 
    'mass_12'           ,
    'mass_13'           ,
    'mass_14'           ,
    'mass_23'           ,
    'mass_24'           ,
    'mass_34'           ,

    'pv_x'              ,
    'pv_y'              ,
    'pv_z'              ,

    'bs_x0'             ,
    'bs_y0'             ,
    'bs_z0'             ,

    'bs_x'              ,
    'bs_y'              ,

    'vx'                ,
    'vy'                ,
    'vz'                ,
    'vtx_chi2'          ,
    'vtx_prob'          ,

    'cos2d'             ,
    'lxy'               ,
    'lxy_err'           ,
    'lxy_sig'           ,

    'mu1_pt'            ,
    'mu1_eta'           ,
    'mu1_phi'           ,
    'mu1_e'             ,
    'mu1_mass'          ,
    'mu1_charge'        ,
    'mu1_id_loose'      ,
    'mu1_id_soft'       ,
    'mu1_id_medium'     ,
    'mu1_id_tight'      ,
    'mu1_id_soft_mva'   ,
    'mu1_dxy'           ,
    'mu1_dxy_e'         ,
    'mu1_dxy_sig'       ,
    'mu1_dz'            ,
    'mu1_dz_e'          ,
    'mu1_dz_sig'        ,
    'mu1_bs_dxy'        ,
    'mu1_bs_dxy_e'      ,
    'mu1_bs_dxy_sig'    ,
    'mu1_cov_pos_def'   ,

    'mu2_pt'            ,
    'mu2_eta'           ,
    'mu2_phi'           ,
    'mu2_e'             ,
    'mu2_mass'          ,
    'mu2_charge'        ,
    'mu2_id_loose'      ,
    'mu2_id_soft'       ,
    'mu2_id_medium'     ,
    'mu2_id_tight'      ,
    'mu2_id_soft_mva'   ,
    'mu2_dxy'           ,
    'mu2_dxy_e'         ,
    'mu2_dxy_sig'       ,
    'mu2_dz'            ,
    'mu2_dz_e'          ,
    'mu2_dz_sig'        ,
    'mu2_bs_dxy'        ,
    'mu2_bs_dxy_e'      ,
    'mu2_bs_dxy_sig'    ,
    'mu2_cov_pos_def'   ,

    'mu3_pt'            ,
    'mu3_eta'           ,
    'mu3_phi'           ,
    'mu3_e'             ,
    'mu3_mass'          ,
    'mu3_charge'        ,
    'mu3_id_loose'      ,
    'mu3_id_soft'       ,
    'mu3_id_medium'     ,
    'mu3_id_tight'      ,
    'mu3_id_soft_mva'   ,
    'mu3_dxy'           ,
    'mu3_dxy_e'         ,
    'mu3_dxy_sig'       ,
    'mu3_dz'            ,
    'mu3_dz_e'          ,
    'mu3_dz_sig'        ,
    'mu3_bs_dxy'        ,
    'mu3_bs_dxy_e'      ,
    'mu3_bs_dxy_sig'    ,
    'mu3_cov_pos_def'   ,

    'mu4_pt'            ,
    'mu4_eta'           ,
    'mu4_phi'           ,
    'mu4_e'             ,
    'mu4_mass'          ,
    'mu4_charge'        ,
    'mu4_id_loose'      ,
    'mu4_id_soft'       ,
    'mu4_id_medium'     ,
    'mu4_id_tight'      ,
    'mu4_id_soft_mva'   ,
    'mu4_dxy'           ,
    'mu4_dxy_e'         ,
    'mu4_dxy_sig'       ,
    'mu4_dz'            ,
    'mu4_dz_e'          ,
    'mu4_dz_sig'        ,
    'mu4_bs_dxy'        ,
    'mu4_bs_dxy_e'      ,
    'mu4_bs_dxy_sig'    ,
    'mu4_cov_pos_def'   ,
]

paths = [
    'HLT_Mu7_IP4'     ,
    'HLT_Mu8_IP3'     ,
    'HLT_Mu8_IP5'     ,
    'HLT_Mu8_IP6'     ,
    'HLT_Mu8p5_IP3p5' ,
    'HLT_Mu9_IP4'     ,
    'HLT_Mu9_IP5'     ,
    'HLT_Mu9_IP6'     ,
    'HLT_Mu10p5_IP3p5',
    'HLT_Mu12_IP6'    ,
]

branches += paths
branches += [path+'_ps' for path in paths]
