branches = [
    'run'                   ,
    'lumi'                  ,
    'event'                 ,
    'npv'                   ,
    'neles'                 ,
    'neecands'              ,
    'ntrigobj'              ,
     
    'mass'                  ,
    'mcorr'                 ,
    'pt'                    ,
    'eta'                   ,
    'phi'                   ,
    'tk_mass'               ,
    'tk_mcorr'              ,
    'tk_pt'                 ,
    'tk_eta'                ,
    'tk_phi'                ,
    'sc_mass'               ,
    'sc_mcorr'              ,
    'sc_pt'                 ,
    'sc_eta'                ,
    'sc_phi'                ,
    'charge'                ,

    'to_mass'               ,
    'to_pt'                 ,
    'to_eta'                ,
    'to_phi'                ,

    'dr'                    ,
    'dr_max'                ,

    'pv_x'                  ,
    'pv_y'                  ,
    'pv_z'                  ,

    'bs_x0'                 ,
    'bs_y0'                 ,
    'bs_z0'                 ,

    'bs_x'                  ,
    'bs_y'                  ,

    'vx'                    ,
    'vy'                    ,
    'vz'                    ,
    'vtx_chi2'              ,
    'vtx_prob'              ,

    'cos2d'                 ,
    'lxy'                   ,
    'lxy_err'               ,
    'lxy_sig'               ,

    'e1_pt'                 ,
    'e1_eta'                ,
    'e1_phi'                ,
    'e1_e'                  ,
    'e1_to_pt'              ,
    'e1_to_eta'             ,
    'e1_to_phi'             ,
    'e1_mass'               ,
    'e1_tk_pt'              ,
    'e1_tk_eta'             ,
    'e1_tk_phi'             ,
    'e1_tk_e'               ,
    'e1_sc_pt'              ,
    'e1_sc_eta'             ,
    'e1_sc_phi'             ,
    'e1_sc_e'               ,
    'e1_charge'             ,
    'e1_id_loose'           ,
    'e1_id_wp90'            ,
    'e1_id_wp80'            ,
    'e1_dxy'                ,
    'e1_dxy_e'              ,
    'e1_dxy_sig'            ,
    'e1_dz'                 ,
    'e1_dz_e'               ,
    'e1_dz_sig'             ,
    'e1_bs_dxy'             ,
    'e1_bs_dxy_e'           ,
    'e1_bs_dxy_sig'         ,
    'e1_cov_pos_def'        ,
    'e1_det_cov'            ,

    'e1_fbrem'              ,
    'e1_deltaetain'         ,
    'e1_deltaphiin'         ,
    'e1_oldsigmaietaieta'   ,
    'e1_oldhe'              ,
    'e1_ep'                 ,
    'e1_olde15'             ,
    'e1_eelepout'           ,
    'e1_kfchi2'             ,
    'e1_kfhits'             ,
    'e1_expected_inner_hits',
    'e1_convDist'           ,
    'e1_convDcot'           ,
    'e1_r9'                 ,
    'e1_r9_5x5'             ,
    'e1_scl_eta'            ,
    'e1_dr03TkSumPt'        ,
    'e1_dr03EcalRecHitSumEt',
    'e1_dr03HcalTowerSumEt' ,
    'e1_pixhits'            ,

    'e2_pt'                 ,
    'e2_eta'                ,
    'e2_phi'                ,
    'e2_e'                  ,
    'e2_to_pt'              ,
    'e2_to_eta'             ,
    'e2_to_phi'             ,
    'e2_mass'               ,
    'e2_tk_pt'              ,
    'e2_tk_eta'             ,
    'e2_tk_phi'             ,
    'e2_tk_e'               ,
    'e2_sc_pt'              ,
    'e2_sc_eta'             ,
    'e2_sc_phi'             ,
    'e2_sc_e'               ,
    'e2_charge'             ,
    'e2_id_loose'           ,
    'e2_id_wp90'            ,
    'e2_id_wp80'            ,
    'e2_dxy'                ,
    'e2_dxy_e'              ,
    'e2_dxy_sig'            ,
    'e2_dz'                 ,
    'e2_dz_e'               ,
    'e2_dz_sig'             ,
    'e2_bs_dxy'             ,
    'e2_bs_dxy_e'           ,
    'e2_bs_dxy_sig'         ,
    'e2_cov_pos_def'        ,
    'e2_det_cov'            ,

    'e2_fbrem'              ,
    'e2_deltaetain'         ,
    'e2_deltaphiin'         ,
    'e2_oldsigmaietaieta'   ,
    'e2_oldhe'              ,
    'e2_ep'                 ,
    'e2_olde15'             ,
    'e2_eelepout'           ,
    'e2_kfchi2'             ,
    'e2_kfhits'             ,
    'e2_expected_inner_hits',
    'e2_convDist'           ,
    'e2_convDcot'           ,
    'e2_r9'                 ,
    'e2_r9_5x5'             ,
    'e2_scl_eta'            ,
    'e2_dr03TkSumPt'        ,
    'e2_dr03EcalRecHitSumEt',
    'e2_dr03HcalTowerSumEt' ,
    'e2_pixhits'            ,

    'trg_match'             ,


]

paths = [
    'HLT_DoubleEle4_eta1p22_mMax6'  ,
    'HLT_DoubleEle4p5_eta1p22_mMax6',
    'HLT_DoubleEle5_eta1p22_mMax6'  ,
    'HLT_DoubleEle5p5_eta1p22_mMax6',
    'HLT_DoubleEle6_eta1p22_mMax6'  ,
    'HLT_DoubleEle6p5_eta1p22_mMax6',
    'HLT_DoubleEle7_eta1p22_mMax6'  ,
    'HLT_DoubleEle7p5_eta1p22_mMax6',
    'HLT_DoubleEle8_eta1p22_mMax6'  ,
    'HLT_DoubleEle8p5_eta1p22_mMax6',
    'HLT_DoubleEle9_eta1p22_mMax6'  ,
    'HLT_DoubleEle9p5_eta1p22_mMax6',
    'HLT_DoubleEle10_eta1p22_mMax6' ,

    'HLT_DoubleEle4_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle4p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle5_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle5p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle6_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle6p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle7_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle7p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle8_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle8p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle9_eta1p22_mMax6_trkHits10'  ,
    'HLT_DoubleEle9p5_eta1p22_mMax6_trkHits10',
    'HLT_DoubleEle10_eta1p22_mMax6_trkHits10' ,

    'HLT_DoubleEle4_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle4p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle5_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle5p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle6_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle6p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle7_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle7p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle8_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle8p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle9_eta1p22_mMax6_dz0p8'  ,
    'HLT_DoubleEle9p5_eta1p22_mMax6_dz0p8',
    'HLT_DoubleEle10_eta1p22_mMax6_dz0p8' ,
]

branches += paths
branches += [path+'_ps' for path in paths]

